//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dominioAnchet.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRAS
    {
        public COMPRAS()
        {
            this.DETALLE_COMPRA = new HashSet<DETALLE_COMPRA>();
        }
    
        public int ID_COMPRA { get; set; }
        public int ID_USUARIO { get; set; }
        public string NOMBRES_PRODUCTOS { get; set; }
        public int COSTO_TOTAL { get; set; }
        public Nullable<System.DateTime> FECHA_COMPRA { get; set; }
        public Nullable<System.DateTime> FECHA_ENTREGA { get; set; }
        public Nullable<bool> PAGADA { get; set; }
        public string MENSAJE { get; set; }
        public string ENTREGAR_A_QUIEN { get; set; }
        public string TITULO_MENSAJE { get; set; }
        public string DE_PARTE_DE { get; set; }
        public string DIRECCION_DE_ENTREGA { get; set; }
        public string TELEFONO_ENTREGA { get; set; }
        public Nullable<int> COD_ESTADO_COMPRA { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
        public virtual ICollection<DETALLE_COMPRA> DETALLE_COMPRA { get; set; }
        public virtual ESTADO_COMPRA ESTADO_COMPRA { get; set; }
    }
}
