//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dominioAnchet.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_COMPRA
    {
        public int ID_DETALLE_COMPRA { get; set; }
        public int ID_COMPRA { get; set; }
        public int ID_PRODUCTO { get; set; }
        public int CANTIDAD { get; set; }
        public int PRECIO_TOTAL { get; set; }
    
        public virtual PRODUCTOS PRODUCTOS { get; set; }
        public virtual COMPRAS COMPRAS { get; set; }
    }
}
