//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dominioAnchet.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_COMPRA
    {
        public ESTADO_COMPRA()
        {
            this.COMPRAS = new HashSet<COMPRAS>();
        }
    
        public int COD_ESTADO_COMPRA { get; set; }
        public string NOMBRE_ESTADO_COMPRA { get; set; }
    
        public virtual ICollection<COMPRAS> COMPRAS { get; set; }
    }
}
