//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dominioAnchet.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnchetasMoritaEntities : DbContext
    {
        public AnchetasMoritaEntities()
            : base("name=AnchetasMoritaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DETALLE_COMPRA> DETALLE_COMPRA { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<USUARIOS> USUARIOS { get; set; }
        public DbSet<PRODUCTOS> PRODUCTOS { get; set; }
        public DbSet<TIPO_PRODUCTO> TIPO_PRODUCTO { get; set; }
        public DbSet<COMPRAS> COMPRAS { get; set; }
        public DbSet<ESTADO_COMPRA> ESTADO_COMPRA { get; set; }
    }
}
