//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dominioAnchet.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_PRODUCTO
    {
        public TIPO_PRODUCTO()
        {
            this.PRODUCTOS = new HashSet<PRODUCTOS>();
        }
    
        public int ID_TIPO_PRODUCTO { get; set; }
        public string NOMBRE_TIPO_PRODUCTO { get; set; }
        public string URL_IMAGEN { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    
        public virtual ICollection<PRODUCTOS> PRODUCTOS { get; set; }
    }
}
