//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dominioAnchet.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public USUARIOS()
        {
            this.COMPRAS = new HashSet<COMPRAS>();
        }
    
        public int ID_USUARIO { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string APELLIDOS_USUARIO { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<int> TELEFONO_FIJO { get; set; }
        public string CELULAR { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public string CORREO_VERIFICADO { get; set; }
        public string ROL { get; set; }
    
        public virtual ICollection<COMPRAS> COMPRAS { get; set; }
    }
}
