using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using kuxan.cls;

namespace kuxan.frm.logica
{
    public partial class frmServicios : clsPaginaGeneral
    {
        protected void Page_Load(object sender, EventArgs e)
        {

        }
       protected void Page_PreRender(object sender, EventArgs e)
        {
            if (this.idiomaActual() == Idioma.English)
            {
                Label1.Text = "Terms of Service";
                Label2.Text = "Kuxan provides the service of its web applications in two modalities, free and paid. Kuxan may stop offering the Free plan for new users, but the user who acquired it before may continue using it indefinitely as long as they do not make changes in your plan. The user acquires a non-exclusive, worldwide and temporary and non-transferable license to use the Kuxan system according to the conditions of the plan that he has chosen at the time of paying for the service, or if applicable, he accepts the conditions that he has Being a free user, but at no time does it acquire ownership of the platform.";
                Label3.Text = "The copyright on the software works that make up the platform and the Services will be owned by Kuxan and under no interpretation of these terms of service will be understood as transferred to the user. ";
                Label4.Text = "The Kuxan service starts when you register an account on the Kuxan website, after having accepted the conditions expressed in this contract";
                Label5.Text = "The user becomes aware of the services for which he is paying when using any of the plans that Kuxan offers. Kuxan will not be responsible in any case for errors made by the user when choose your plan, as well as when typing or entering your personal information as well as the operation and progress of your business activity or the classification you make of it, which will irremediably affect the results produced by the Software.";
                Label6.Text = "Kuxan understands that the account holder and users are aware of any changes made to the account settings, and that they will make the changes they deem appropriate. Kuxan will not be held responsible for the loss of information that occurs due to force majeure, fortuitous event or act of a third party as explained under the heading Operation of the Site";
                 Label7.Text = "Scope and level of service";
                Label8.Text = "Under normal conditions, the Kuxan platform has a down time of approximately 1%, so that the platform is available 99% of the time. Kuxan will take steps that it deems appropriate, to that the application is available to the user, but it does not guarantee the foregoing, since there may be events such as damage to communications, acts of third parties, maintenance or restructuring of the application, among others, that are beyond the control and responsibility of Kuxan. Notwithstanding the foregoing, Kuxan guarantees users that the application will be available under normal circumstances, as announced, from anywhere in the world that allows an Internet connection, as long as the user remembers their account credentials and the conditions of provision. of the Internet connection service by each provider, allow it. ";
                Label9.Text = "In such a way that if it could not be accessed due to the type of connection or due to the deficient service of the aforementioned provider, this does not imply at any time a breach of the service provided by Kuxan. ";
                Label10.Text = "Regarding the maintenance and restructuring of the application, Kuxan reserves the right to carry out the necessary steps, without prior notice to users, but will ensure that they are given notice as early as in their opinion consider convenient or prudent to avoid inconvenience or eventual damage in the processing of data or information.";
                Label11.Text = "Means of payment";
                Label12.Text = "The user will be able to choose the plan and payment period at the time of making the first payment. Depending on the chosen period: monthly, semi-annual or annual, the next charge will be made on the same day of the month in which he signed up.";
                Label13.Text = "Kuxan's payment is in advance and the user accepts that recurring charges are made according to the chosen periods. He also agrees to notify Kuxan in case he does not want the next charge to be generated, at least 2 business days before your next billing date.";
                Label14.Text = "In the event that the user does not notify Kuxan in advance of his desire not to generate the recurring charge, he will have 5 business days to request the return of the money in accordance with the right of withdrawal provided for in the Consumer Statute . ";
                Label15.Text = "Kuxan offers the means of payment that are listed on its website. However, to access Kuxan through some of these payment systems, it may be necessary for the account holder to register some information , such as an account number or credit card issued by a financial institution or that is in force, in order to charge for the services provided in our online software. If there are withholdings of any kind, these will have to be assumed by the user.";
                Label16.Text = "Kuxan is aware that holding user credit card or bank account information is sensitive. Therefore, it is committed to keeping this information safe and isolated from improper use.";
                Label17.Text = "Kuxan assumes that the credit card information entered to create an account is known by the account holder, therefore it is not responsible for the inappropriate use of credit cards at the time of this being used to register an account, understood as irresponsible use, falsification and impersonation of the identity of the account holder.";
                Label18.Text = "Kuxan, therefore, refrains from carrying out all kinds of acts aimed at carrying out the verification of the User's personal data to compare them with those registered on his credit card, since he assumes that whoever provides the They themselves are their own owner and therefore know data to which no person has access, in addition to not having databases with which to compare such information.";
                Label19.Text = "Notwithstanding this, the user authorizes Kuxan to carry out any verification or consultation of their data in any database, information and risk centers and any other source of information that provides history on the form in which it meets its financial and credit commitments, both nationally and internationally.";
                Label20.Text = "The user affirms under oath that he is not included in the Clinton List and that his income is not related to any type of acts that Colombian and international legislation determines for money laundering, drug trafficking , terrorism or other crime and that are legally acquired. ";
            }
            else
            {
                Label1.Text = "Condiciones del servicio";
                Label2.Text = "Kuxan presta el servicio de sus aplicaciones web en dos modalidades, gratis y pago. Kuxan podrá dejar de ofrecer el plan Gratis para usuarios nuevos, pero el usuario que lo adquirió antes podrá seguir usándolo indefinidamente siempre y cuando no realice cambios posteriores en su plan.  El usuario adquiere una licencia no-exclusiva, mundial y temporal e intransferible para usar el sistema Kuxan según las condiciones del plan que haya elegido al momento de pagar por el servicio, o si es el caso acepta las condiciones que tiene al ser un usuario gratis, pero en ningún momento adquiere propiedad sobre la plataforma. ";
                Label3.Text = "Los derechos de autor sobre las obras de software que componen la plataforma y los Servicios serán de titularidad de Kuxan y bajo ninguna interpretación de éstos términos de servicio se entenderán transferidos al usuario. ";
                Label4.Text = "El servicio de Kuxan se inicia al momento de registrar una cuenta en el sitio web de Kuxan, tras haber aceptado las condiciones expresadas en este contrato";
                Label5.Text = "El usuario se hace conocedor de los servicios por los que está pagando a la hora de usar alguno de los planes que ofrece Kuxan. Kuxan no se hará responsable en ningún caso por los errores cometidos por el usuario a la hora de elegir su plan, así como tampoco al momento de digitar o ingresar su información tanto personal como de la operación y marcha de su actividad empresarial ni tampoco de la clasificación que realice de la misma lo que afectará irremediablemente los resultados arrojados por el Software. ";
                Label6.Text = "Kuxan da por entendido que el titular de la cuenta y los usuarios conocen cualquier cambio que se haga en la configuración de ésta, así como que realizará los cambios que considere pertinentes. Kuxan no se responsabilizará por la pérdida de información que ocurra por fuerza mayor, caso fortuito o hecho de un tercero tal y como se explica bajo el título “Operación del Sitio";
                Label7.Text = "Alcance y nivel de servicio";
                Label8.Text = "En condiciones normales, la plataforma de Kuxan tiene un “down time” de aproximadamente 1%, de modo que la plataforma se encuentra disponible el 99%  del tiempo. Kuxan adelantará las gestiones que a su juicio estime conducentes, para que la aplicación esté disponible para el usuario, pero no garantiza lo anterior, por cuanto pueden existir eventos como daños en las comunicaciones, actos de terceros, mantenimiento o reestructuración de la aplicación, entre otros, que escapen al control y responsabilidad de Kuxan. No obstante lo anterior, Kuxan garantiza a los usuarios que la aplicación estará disponible en circunstancias normales, según lo anunciado, desde cualquier lugar del mundo que permita una conexión a Internet, siempre y cuando el usuario recuerde las credenciales de su cuenta y las condiciones de prestación del servicio de conexión a Internet por parte de cada proveedor, lo permitan. ";
                Label9.Text = "De manera tal que si no se pudiera acceder por el tipo de conexión o por el deficiente servicio del mencionado proveedor, ello no implica en ningún momento incumplimiento de la prestación del servicio prestado por parte de Kuxan. ";
                Label10.Text = "En cuanto al mantenimiento y reestructuración de la aplicación, Kuxan se reserva el derecho de llevar a cabo las gestiones necesarias, sin previo aviso a los usuarios, pero procurará que se les brinde un aviso con la antelación que a su juicio considere conveniente o prudente para evitar incomodidades o eventuales perjuicios en el procesamiento de datos o de información.";
                Label11.Text = "Medios de pago";
                Label12.Text = "El usuario podrá elegir el plan y periodo de pago al momento de realizar el primer pago. Según el periodo elegido: mensual, semestral o anual, el próximo cobro se realizará el mismo día del mes en que se inscribió.";
                Label13.Text = "El pago de Kuxan es anticipado y el usuario acepta que se realicen cobros recurrentes según los periodos elegidos. Además se compromete a notificar a Kuxan en caso tal de que no quiera que se genere el siguiente cobro, mínimo 2 días hábiles antes de sur próxima fecha de cobro.";
                Label14.Text = "En caso de que el usuario no notifique a Kuxan, con anticipación sobre su deseo de no generar el cobro recurrente, este tendrá 5 días hábiles para pedir la devolución del dinero conforme el derecho de retracto previsto en el Estatuto del Consumidor. ";
                Label15.Text = "Kuxan ofrece los medios de pago que se reseñan en su página web.. Sin embargo, para acceder a Kuxan a través de algunos de estos sistemas de pago, puede ser necesario registrar por parte del titular de la cuenta alguna información, como por ejemplo un número de cuenta o  tarjeta de crédito expedida por parte de una entidad financiera o que se encuentre vigente, para poder realizar el cobro por los servicios prestados en nuestro software online, Si existen retenciones de cualquier tipo estas tendrán que ser asumidas por el usuario. ";
                Label16.Text = "Kuxan es consciente que poseer información de tarjetas de crédito o cuentas bancarias de los usuarios es delicado. Por lo tanto está comprometido con mantener esta información segura y aislada de usos inadecuados.";
                Label17.Text = "Kuxan da por hecho que la información de la tarjeta de crédito ingresada para crear una cuenta es conocida por el titular de la cuenta por lo tanto no se hace responsable por el uso inadecuado de tarjetas de crédito al momento de esta ser usada para registrar una cuenta, entendiéndose como uso irresponsable, la falsificación y suplantación de la identidad del titular la cuenta. ";
                Label18.Text = "Kuxan, por lo tanto, se abstiene de llevar a cabo todo tipo de actos tendientes a llevar a cabo la verificación de los datos personales del Usuario para confrontarlos con los registrados en su tarjeta de crédito pues asume que quien brinde los mismos es su propio titular y por ello conoce datos a los que no tiene acceso cualquier persona, además de no tener bases de datos con las cuales confrontar tal información. ";
                Label19.Text = "No obstante esto, el usuario autoriza a Kuxan a llevar a cabo cualquier verificación o consulta de los datos suyos en cualquier base de datos, centrales de información y riesgo y cualquier otra fuente de información que le brinde historia sobre la forma en la que atiende sus compromisos financieros y crediticios, tanto en el ámbito nacional como en el internacional.";
                Label20.Text = "El usuario afirma bajo la gravedad de juramento, que no está incluido en la Lista Clinton y que sus ingresos no tienen relación con ningún tipo de actos de aquellos que la legislación colombiana e internacional determinan para el lavado de activos, narcotráfico, terrorismo ni otro delito y que son adquiridos de manera lícita. ";
            }
        }
    }
}